### ISSUE TITLE
Failed to resolve: com.github.yalantis:ucrop:2.2.5 

### ISSUE THREAD

**Issue by Mr-Ramzan** [Dhaval2404/ImagePicker#100]
I have a project this lib is working like a charm. 
on a new project, this error pops up failing the Gradle build

           "Failed to resolve: com.github.yalantis:ucrop:2.2.5" 

Minimum Sdk version is 16,
Max to the latest.

**Comment by Dhaval2404** [comment]
@Mr-Ramzan Please make sure, you have the following in project build.gradle file

```
allprojects {
   repositories {
      	jcenter()
       	maven { url "https://jitpack.io" }  //Make sure to add this in your project for uCrop
   }
}
```
