### ISSUE TITLE
HOW TO CHANGE TOOLBAR TITLE COLOR!

### ISSUE THREAD

**Issue by umairrmustafa** [Dhaval2404/ImagePicker#101]
Hi there, I am not able to change the Toolbar text color.

**Comment by Dhaval2404** [comment]
**Toolbar Icon & Text Color:**
```xml
<color name="ucrop_color_toolbar_widget">@color/red_500</color>
```

**Toolbar Background Color:**
```xml
<color name="ucrop_color_toolbar">@color/blue_500</color>
```

**Statusbar Color:**
```xml
<color name="ucrop_color_statusbar">@color/blue_500</color>
```

![Screenshot_1608381911](https://user-images.githubusercontent.com/7314181/102689750-83103500-4226-11eb-9f12-685ac6f664a2.png)

**Comment by sahinkarakulak** [comment]
Hello, I want to edit the text that says "Edit Photo" How can I do that?
