### ISSUE TITLE
Click Listener on Cancel, Camera, and Gallery

### ISSUE THREAD

**Issue by lobothijau** [Dhaval2404/ImagePicker#102]
Is it possible to listen to cancel button, camera and gallery button?

**Comment by Dhaval2404** [comment]
@lobothijau You can listen to Camera and Gallery Button Click:

ImagePicker.with(this)
                // Intercept selected ImageProvider
                .setImageProviderInterceptor { imageProvider ->  
                        // imageProvider will be either ImageProvider.GALLERY or ImageProvider.CAMERA
                }
                .start()
