### ISSUE TITLE
Toolbar Text and Buttons color

### ISSUE THREAD

**Issue by somesh-ss** [Dhaval2404/ImagePicker#111]
Is there any color resource value that can be use to change the color of the text on the tool bar and the tick/cross button?
If there is no such value already could you please add one and let me know how I could achieve it?

**Comment by Dhaval2404** [comment]
**Toolbar Icon & Text Color:**
```xml
<color name="ucrop_color_toolbar_widget">@color/red_500</color>
```

**Toolbar Background Color:**
```xml
<color name="ucrop_color_toolbar">@color/blue_500</color>
```

**Statusbar Color:**
```xml
<color name="ucrop_color_statusbar">@color/blue_500</color>
```

![Screenshot_1608381911](https://user-images.githubusercontent.com/7314181/102689750-83103500-4226-11eb-9f12-685ac6f664a2.png)
