### ISSUE TITLE
Can you add free hand cropping ?

### ISSUE THREAD

**Issue by EleshBaraiya** [Dhaval2404/ImagePicker#112]
I want to freehand cropping so need to just add one line codding in your code setFreeStyleCropEnabled(true)

**Comment by Dhaval2404** [comment]
Duplicate of #76

**Comment by maleeqB** [comment]
How is this supposed to be a duplicate? UCrop is still being used by this library and UCrop#Options support setFreeStyleCropEnabled(boolean)



no such way to own CropProvider, UCrop options or anything
