### ISSUE TITLE
Same image in 2 imageviews

### ISSUE THREAD

**Issue by shree-vastava** [Dhaval2404/ImagePicker#113]
If I have 2 imageviews in same screen, how shall I identify in onActivityForResult, since it always returns same request code.
So If I have two imageviews in same screen and I pick and image, same image is shown in both imageviews.

**Comment by Dhaval2404** [comment]
Please check customization section of ReadMe:

![image](https://user-images.githubusercontent.com/7314181/90719307-a5726000-e2d1-11ea-8ca3-d741dc6ae5f4.png)
