### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by iusama46** [Dhaval2404/ImagePicker#119]
Hello, Add Dark mode support in Dialog

**Comment by Dhaval2404** [comment]
@iusama46 Dark Mode is already supported in Dialog? Are you facing any issue here?

**Comment by iusama46** [comment]
Camera/Gallery icon & text does not look good. Is there any way to change text & icon color for dark mode?

**Comment by Dhaval2404** [comment]
@iusama46 Please add below resource in your values-night color resources:

    <color name="dialog_choose_icon_color">#757575</color>
    <color name="dialog_choose_text_color">#757575</color>

**Comment by iusama46** [comment]
Okay,Thanks
