### ISSUE TITLE
How can I changed the Folder location

### ISSUE THREAD

**Issue by wazeem910** [Dhaval2404/ImagePicker#120]
it is always choose
storage/emmulated/DCIM.......
How can i change this ?
Plus if i get the file path how can i send it to server ?

**Comment by Dhaval2404** [comment]
@wazeem910 You can specify the store directory by saveDir method. 

```
ImagePicker.with(this)
    //Provide directory path to save images
    .saveDir(File(Environment.getExternalStorageDirectory(), "ImagePicker"))
    // .saveDir(Environment.getExternalStorageDirectory())
    // .saveDir(getExternalFilesDir(null)!!)
    .start()
```

**Comment by AbhishekDere** [comment]
This Does not work in Java, please help!

**Comment by Dhaval2404** [comment]
@AbhishekDere Can you explain what is not working for you? I'm here to help you!

**Comment by AbhishekDere** [comment]
> @AbhishekDere Can you explain what is not working for you? I'm here to help you!

Hey, Thanks for the Reply. The problem is with my Java thing. Whener I use onlyCamera function, I place the .saveDir(new File(Environment.getExternalDirectory(),"Folder123"))
This Creates the Folder123 but it does not save the image.

**Comment by Dhaval2404** [comment]
@AbhishekDere Thank you for the quick reply. I will get back to you before the end of day.

**Comment by Dhaval2404** [comment]
@AbhishekDere Can you please tell me which ImagePicker version you're working on?

**Comment by AbhishekDere** [comment]
> @AbhishekDere Can you please tell me which ImagePicker version you're working on?

1.7.5

**Comment by Dhaval2404** [comment]
@AbhishekDere Can you please try this code:

```Java
ImagePicker.Companion.with(this)
                   .saveDir(new File(Environment.getExternalStorageDirectory(), "Folder123"))
                    .start();

Also, Please add the below code in your activity or fragment. and let me know if shows any error or print path.

```Java
@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == Activity.RESULT_OK) {
            Log.e("TAG", "Path:"+ImagePicker.Companion.getFilePath(data));
        } else if (resultCode == ImagePicker.RESULT_ERROR) {
            Toast.makeText(this, ImagePicker.Companion.getError(data), Toast.LENGTH_SHORT).show();
        } else {
            Toast.makeText(this, "Task Cancelled", Toast.LENGTH_SHORT).show();
        }
    }

**Comment by AbhishekDere** [comment]
Cool, thanks for the snippet! Really Appreciate it
