### ISSUE TITLE
Crash on the cropping page when taking high resolution images (64MP)

### ISSUE THREAD

**Issue by guy-4444** [Dhaval2404/ImagePicker#122]
I try to take a picture from the camera but when I take 64mp picture it crash on the cropping page.
i try with the same device with front camera (32MP), everything ok.

Guy.

**Comment by hbb20** [comment]
It will be better to address this sooner since new devices are having high res camera. May be it's a not really an issue of this library though since it uses other library for crop.

**Comment by hbb20** [comment]
Compressing before sending to the image cropper might be an effort that can be done from this library.

**Comment by Dhaval2404** [comment]
@hbb20 I will try to fix this over the weekend. Thank you so much for the hint.

**Comment by hbb20** [comment]
Hey, this might be helpful to you. Looks like [2.2.6 of uCrop](https://github.com/Yalantis/uCrop/issues/648#issuecomment-681890665) has this fixed. So uCrop update from 2.2.5 to 2.2.6 in this project should fix this.

**Comment by hbb20** [comment]
FYI: I added 2.2.6 of uCrop in addition to imagepicker in my project and it worked for high res images. So may be that's all you will need to do.. update uCrop from 2.2.5 to 2.2.6 👍
