### ISSUE TITLE
Failed to crop..issue

### ISSUE THREAD

**Issue by DeveloperAsh** [Dhaval2404/ImagePicker#123]
When select image from gallery then try to select ..getting toast of Failed to crop and get closed intent.

-----How i call
 ImagePicker.Companion.with(AddCategoryUi.this)
                        .compress(1024)			//Final image size will be less than 1 MB(Optional)
                        .crop()
                        .start();

----Dependency
implementation 'com.github.dhaval2404:imagepicker-support:1.7.1'
    implementation 'com.github.yalantis:ucrop:2.2.2'

**Comment by Dhaval2404** [comment]
@DeveloperAsh What is your targetSdkVersion?
