### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by soareseneves** [Dhaval2404/ImagePicker#13]
Hey there,

I think you forgot to bump the version after your last commit, I can't get the new features using version 1.1

**Comment by Dhaval2404** [comment]
@soareseneves I'm yet to upload the lib on jcenter. I will update the version after the lib upload.
Thanks

**Comment by soareseneves** [comment]
Oh, ok, I will wait for it then :P, I hope you don't mind but I'm implementing your library into a Form Library: https://github.com/TheJuki/KFormMaster, I will send a PR to TheJuki after you upload the version!

Thanks for this great library!

**Comment by Dhaval2404** [comment]
@soareseneves Sure, Will do it in max 2-3 hours.

**Comment by soareseneves** [comment]
Take your time :)

**Comment by Dhaval2404** [comment]
@soareseneves v1.2 is live now. Thanks
