### ISSUE TITLE
"faild to crop image"

### ISSUE THREAD

**Issue by MrAndroi** [Dhaval2404/ImagePicker#132]
i have a problem when i select image from camera or gallary its shows a toast "faild to crop image"

**Comment by Dhaval2404** [comment]
@MrAndroi Can you please provide more detail on the issue? Are you testing on Android 10 or 11?

**Comment by MrAndroi** [comment]
yes android 10

**Comment by Dhaval2404** [comment]
Did you add **android:requestLegacyExternalStorage="true"** in manifest?

![image](https://user-images.githubusercontent.com/7314181/97040511-ac487800-158b-11eb-859f-917a819294bb.png)

**Comment by MrAndroi** [comment]
oh yea thank you its work after i add it
