### ISSUE TITLE
image picker saves picture every time

### ISSUE THREAD

**Issue by yamin8000** [Dhaval2404/ImagePicker#136]
image picker saves picture every time I select and compress a picture, is there anyway to prevent it from saving pictures or auto-delete them?

**Comment by Dhaval2404** [comment]
@yamin8000 This looks like a project-specific requirement. The thing, I will recommend is to delete the picture after your use case has been fulfilled.

For example, If you're using this library for uploading profile image. You can delete the image after you get a successful response from API calls. The only thing you need to take care of is to check the image source before delete. Make sure that you don't delete the gallery image which the user has chosen. The easiest option is to check the file modified time. Else you can specify the saveDir to store the captured or compressed image and later check the file path of it.

Hope this makes sense.  Let me know if you have any queries regarding the same.

Thank you!
