### ISSUE TITLE
I have three imageviews on some devices selecting one image disappears other selected images in other imageviews.

### ISSUE THREAD

**Issue by ajinkyaw** [Dhaval2404/ImagePicker#138]
I am capturing images using the following code

     ImagePicker.Companion.with(NewCustomActivity.this)
                            .compress(300)
                            .cameraOnly()
                            .start(1);

the request code in start(request code) is different for all three imageviews.
then i process them using the below code.

   if (requestCode == 1) {

                    File mainFile = ImagePicker.Companion.getFile(data);
                    if (null != mainFile && null != ImagePicker.Companion.getFile(data).getPath()) {
                        Picasso.get()
                                .load(mainFile)
                                .fit()
                                .centerCrop()
                                .into(myImageView1);
                    } else {
                        myImageView1.setImageResource(R.drawable.image_default);
                    }

    }

On some devices a strange behaviour is observed. 
In my case all three images has to be captures, sometimes after capturing image for one imageview another imageview's selected image gets disappeared.

Can anyone please guide me on this issue ??

I am using this code on android 9 and 10. and issue is observed on both os.

**Comment by hitesh-dhamshaniya** [comment]
You did not face this issue for every device, right?
Can you please provide device make and model, it would be a great help to debug and reproduce the issue.

**Comment by Dhaval2404** [comment]
@ajinkyaw I guess you're facing a low memory issue in some devices you mentioned. You can reproduce this scenario for all devices by enabling **Don't keep activities** from the Developer options.

You might want to save your activity state using ```onSaveInstanceState```. Here is a good example to start with: [how-to-use-onsavedinstancestate-example-please](https://stackoverflow.com/questions/6525698/how-to-use-onsavedinstancestate-example-please)

Do let me know if this fixes your issue. I will be happy to help you.

Thank you!

**Comment by Dhaval2404** [comment]
@ajinkyaw I Hope the above solution works for you. Alternatively you can use ViewModel to store File value that way also ViewModel will preserver your picked file and in the onCreate method check file value is not null set ImageView.

I'm closing this issue now. Feel free to reopen if you're still facing the issue.

Thank you!
