### ISSUE TITLE
Ques: Customize Dialog appearance 

### ISSUE THREAD

**Issue by kdani41** [Dhaval2404/ImagePicker#144]
Hi, 

Thanks for making & maintaining this library.

> Is there any way to change the text appearance of the camera and choose button dialog?  I want to apply a custom font to it.

 
> Also looks like the cancel button color picks up the primary color from my theme is there any way to change it specifically for the dialog?

![button-color-issue](https://user-images.githubusercontent.com/7985118/103178161-64292880-484e-11eb-8c81-0489e9a02131.png)

**Comment by Dhaval2404** [comment]
@kdani41 If you want to change color, You can use the below resource in your color.xml [#59](https://github.com/Dhaval2404/ImagePicker/issues/59)

```xml
<color name="dialog_choose_icon_color">#757575</color>
<color name="dialog_choose_text_color">#757575</color>
```

The customization option is not available. Here, I will suggest creating a dialog as per your preference and call the ImagePicker method on submit action. Here is the sample code to get you started!

```kotlin

/**
 * Show Image Provide Picker Dialog. Customize it as per your need
 */
fun showChooseAppDialog(
    activity: FragmentActivity, listener: (ImageProvider) -> Unit
) {
    val layoutInflater = LayoutInflater.from(activity)
    val customView = layoutInflater.inflate(R.layout.dialog_choose_app, null)

    val dialog = AlertDialog.Builder(activity)
        .setTitle(R.string.title_choose_image_provider)
        .setView(customView)
        .setCancelable(false)
        .show()

    // Handle Camera option click
    customView.findViewById<View>(R.id.lytCameraPick).setOnClickListener {
        listener.invoke(ImageProvider.CAMERA)
        dialog.dismiss()
    }

    // Handle Gallery option click
    customView.findViewById<View>(R.id.lytGalleryPick).setOnClickListener {
        listener.invoke(ImageProvider.GALLERY)
        dialog.dismiss()
    }
}
```

Usage:
```kotlin
showChooseAppDialog(this) { provider->
    ImagePicker.with(this)
        .provider(provider)
        .start()
}

**Comment by kdani41** [comment]
Make sense thanks for the prompt reply.

**Comment by kdani41** [comment]
Not related but do you know how to change the color for the bottom  controller bar https://github.com/Yalantis/uCrop/issues/729?

**Comment by Dhaval2404** [comment]
I guess you not using v1.8. Anyway please add this to color resource

```xml
<color name="ucrop_color_widget_background">#FFFFFF</color>

**Comment by kdani41** [comment]
@Dhaval2404  I am using 1.8. Adding  `ucrop_color_widget_background`  changes the bottom option bar(the one with 2 icons) color not the rotator bar color

**Comment by Dhaval2404** [comment]
@kdani41 Got it! I guess you need to update the followings

```xml
    <color name="ucrop_color_widget_active">@color/red_500</color>
    <color name="ucrop_color_inactive_controls_color">@color/blue_500</color>

**Comment by kdani41** [comment]
@Dhaval2404 
`ucrop_color_widget_active` -> this changes the active color of icon. Ex -> scale icon & text along with the middle active indicator on the bar.
`ucrop_color_inactive_controls_color` -> this is the default color of those icons when they are in inactive state.

**Comment by Dhaval2404** [comment]
@kdani41 You can check the uCrop [color.xml](https://github.com/Yalantis/uCrop/blob/develop/ucrop/src/main/res/values/colors.xml) file to check other color options.

```xml
    <color name="ucrop_color_progress_wheel_line">@color/red_500</color>
```

![Screenshot_1609423818](https://user-images.githubusercontent.com/7314181/103413567-2a368a00-4ba0-11eb-8131-6ea09f3e0bd5.png)
