### ISSUE TITLE
camera cant show

### ISSUE THREAD

**Issue by souleateryx** [Dhaval2404/ImagePicker#146]
sorry, i know what happened. case close

**Comment by Dhaval2404** [comment]
Ha haa! Can you please add a fix here? Someone might find that useful.

**Comment by deanwinchester4848** [comment]
Can you share it ?
I Have same Problem

**Comment by WarrenFaith** [comment]
@souleateryx can you explain what happened and how you solved it? I might have a similiar or same issue at #162

**Comment by WarrenFaith** [comment]
FYI: A possible solution might have been to use queries in the manifest like mentioned at #143
