### ISSUE TITLE
I need a thumbnail image for displaying a small icon on user interface.

### ISSUE THREAD

**Issue by rotaru01** [Dhaval2404/ImagePicker#150]

**Comment by Dhaval2404** [comment]
This is out of the scope of ImagePicker.

This StackOverflow link might be useful to you:
[https://stackoverflow.com/questions/5548645/get-thumbnail-uri-path-of-the-image-stored-in-sd-card-android](https://stackoverflow.com/questions/5548645/get-thumbnail-uri-path-of-the-image-stored-in-sd-card-android)

Thank you!
