### ISSUE TITLE
Image is compressing a lot

### ISSUE THREAD

**Issue by gauravarora90** [Dhaval2404/ImagePicker#155]
Hi Dhaval,
 
    I am using your image picker library and the images are compressing a lot that they are difficult to read or see. Can you please verify the configuration once?

`

 ImagePicker.with(fragment)
            // Crop Image(User can choose Aspect Ratio)
            // User can only select image from Gallery
            .galleryOnly()

            .galleryMimeTypes(  //no gif images at all
                mimeTypes = arrayOf(
                    "image/png",
                    "image/jpg",
                    "image/jpeg"
                )
            )
            .compress(10240)
            // Image resolution will be less than 1080 x 1920
            .maxResultSize(1920, 1920)
            .start(requestCode)

`

Thanks
Gaurav Arora

**Comment by Dhaval2404** [comment]
@gauravarora90 What do you mean by **images are compressing a lot that they are difficult to read or see**?

**Comment by gauravarora90** [comment]
Yes, they are very difficult to see and read. All are blurred when selected.

**Comment by hitesh-dhamshaniya** [comment]
Can you please upload any image which compressing a lot?

**Comment by Dhaval2404** [comment]
The issue has been fixed in v2.0. 

Ref issue: #152 

Ref commit: [d0d7ecc38c9758955830d91c72de8ad8b849b21f](https://github.com/Dhaval2404/ImagePicker/commit/d0d7ecc38c9758955830d91c72de8ad8b849b21f)

**Comment by inambutt487** [comment]
Hi @Dhaval2404  To select document photographs from the gallery and camera and upload them to the server as Multipart, I'm using the configuration you see below.

For this configuration camera, the image size is 400KB, however the quality is poor and the image is overly compressed, giving me a 357 by 400 resolution. I so need an image that is no larger than 1 MB and is clear. Could you please examine the configuration below and provide further guidance?

ImagePicker.with(this)
        .compress(1024)			
        .maxResultSize(700, 700)
        .start()
