### ISSUE TITLE
Not Importing ing AS 4.2

### ISSUE THREAD

**Issue by jordge06** [Dhaval2404/ImagePicker#156]
I already added all the depedency in my project but still its not popping up in suggestion when I type in ImagePicker. Do I have to import it manually if so what should I type in. Im using Java, minimum sdk 21. Thank You.

**Comment by WarrenFaith** [comment]
Can you try to use a fantasy version number (like "99.88.77") to see if the build complains that it can't be found?
If that is the case we can assume that the dependency is added correctly.
If not please share some details of your build.gradle file(s).

**Comment by hitesh-dhamshaniya** [comment]
Can you please try adding the below method and import manually. Clean the project and try to run the app. 
```
import com.github.dhaval2404.imagepicker.ImagePicker

fun pickGalleryImage(view: View) {
        ImagePicker.with(this)
            // Crop Image(User can choose Aspect Ratio)
            .crop()
            // User can only select image from Gallery
            .galleryOnly()

            .galleryMimeTypes(  //no gif images at all
                mimeTypes = arrayOf(
                    "image/png",
                    "image/jpg",
                    "image/jpeg"
                )
            )
            // Image resolution will be less than 1080 x 1920
            .maxResultSize(1080, 1920)
            .start(GALLERY_IMAGE_REQ_CODE)
    }
```
and If it does not work then please share your Gradle.
