### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by serrokitskiy** [Dhaval2404/ImagePicker#17]
Hello. How i can localization your lib? I need change "Edit Photo" to my language
![Screenshot_20190607-172329](https://user-images.githubusercontent.com/13848224/59111427-b1326a80-8949-11e9-9d86-848af46a2983.png)

**Comment by Dhaval2404** [comment]
Add  `<string name="ucrop_label_edit_photo">Edit Photo</string>` in your string.xml with localized language.

**Comment by serrokitskiy** [comment]
@Dhaval2404 Thanks! And how I can localized "Camera" and "Gallery"

**Comment by Dhaval2404** [comment]
@serrokitskiy Please check this [link](https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/res/values/strings.xml) for string localization. You can override the string as per your need.

**Comment by serrokitskiy** [comment]
@Dhaval2404 Thanks!

**Comment by mahyari** [comment]
`<string name="ucrop_label_edit_photo">Edit Photo</string>` not works for me, It's not available in strings.xml file too.
