### ISSUE TITLE
can we choose multiple images at one time from gallery ?

### ISSUE THREAD

**Issue by rinathakkar** [Dhaval2404/ImagePicker#172]

**Comment by hitesh-dhamshaniya** [comment]
@rinathakkar I think this is an enhancement, not an issue. Kindly check for a single image and if you come across with crash/bug, report it, with an error stack trace. Thank you.

**Comment by lmj0011** [comment]
@rinathakkar [this fork](https://github.com/Harmanbeer007/ImagePicker/commits/master) seems to have implemented this

**Comment by rinathakkar** [comment]
@lmj0011 Thank you

**Comment by Dhaval2404** [comment]
Duplicate of #3
