### ISSUE TITLE
Override texts

### ISSUE THREAD

**Issue by rmlz** [Dhaval2404/ImagePicker#177]
Hello guys! I'm new to the library and would like to change the texts shown texts (such as "Choose" and "Gallery") to my native language. Is there any way I can override the texts (like the strings.xml txts)?

Thanks in advance.

**Comment by Dhaval2404** [comment]
Thank you @hitesh-dhamshaniya for the feedback. @rmlz hope your question is answered. Please add a comment below if you need more help. Closing this issue for now.
