### ISSUE TITLE
onActivityResult deprecated. How to handle it now?

### ISSUE THREAD

**Issue by javimar** [Dhaval2404/ImagePicker#180]

**Comment by HosseinKurd** [comment]
Hi
Please use :

```            val someActivityResultLauncher = registerForActivityResult(
                StartActivityForResult(),
                ActivityResultCallback<ActivityResult> { result ->
                    if (result.resultCode == Activity.RESULT_OK) {
                        //Image Uri will not be null for RESULT_OK
                        val fileUri = result.data?.data
                        // imgProfile.setImageURI(fileUri)

                        //You can get File object from intent
                        val file: File = ImagePicker.getFile(result.data)!!

                        //You can also get File Path from intent
                        val filePath: String = ImagePicker.getFilePath(result.data)!!
                    } else if (result.resultCode == ImagePicker.RESULT_ERROR) {
                        Logger.e(TAG, "registerForActivityResult --> RESULT_ERROR : ${ImagePicker.getError(result.data)}")
                    } else {
                        Logger.e(TAG, "registerForActivityResult --> Operation Canceled!")
                    }
                })

**Comment by kdomingo** [comment]
> Hi
> Please use :
> 
> ```
>                 StartActivityForResult(),
>                 ActivityResultCallback<ActivityResult> { result ->
>                     if (result.resultCode == Activity.RESULT_OK) {
>                         //Image Uri will not be null for RESULT_OK
>                         val fileUri = result.data?.data
>                         // imgProfile.setImageURI(fileUri)
> 
>                         //You can get File object from intent
>                         val file: File = ImagePicker.getFile(result.data)!!
> 
>                         //You can also get File Path from intent
>                         val filePath: String = ImagePicker.getFilePath(result.data)!!
>                     } else if (result.resultCode == ImagePicker.RESULT_ERROR) {
>                         Logger.e(TAG, "registerForActivityResult --> RESULT_ERROR : ${ImagePicker.getError(result.data)}")
>                     } else {
>                         Logger.e(TAG, "registerForActivityResult --> Operation Canceled!")
>                     }
>                 })
> ```

How do we integrate that with the current picker? there seems to be no way.

**Comment by Dhaval2404** [comment]
1. Add required dependency for registerForActivityResult API

 ```groovy
implementation "androidx.activity:activity-ktx:1.2.3"
implementation "androidx.fragment:fragment-ktx:1.3.3"
```

2. Declare this method inside fragment or activity class

```kotlin
private val startForProfileImageResult =
    registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result: ActivityResult ->
        val resultCode = result.resultCode
        val data = result.data

        if (resultCode == Activity.RESULT_OK) {
            //Image Uri will not be null for RESULT_OK
            val fileUri = data?.data!!

            mProfileUri = fileUri
            imgProfile.setImageURI(fileUri)
        } else if (resultCode == ImagePicker.RESULT_ERROR) {
            Toast.makeText(this, ImagePicker.getError(data), Toast.LENGTH_SHORT).show()
        } else {
            Toast.makeText(this, "Task Cancelled", Toast.LENGTH_SHORT).show()
        }
    }
 ```

3. Create ImagePicker instance and launch intent

```kotlin
ImagePicker.with(this)
        .compress(1024)         //Final image size will be less than 1 MB(Optional)
        .maxResultSize(1080, 1080)  //Final image resolution will be less than 1080 x 1080(Optional)
        .createIntent { intent ->
            startForProfileImageResult.launch(intent)
        }
```

**Comment by bhujelaayushgc** [comment]
How would this be done in Java. I am trying to call `createIntent` but don't know how.
