### ISSUE TITLE
How to start a crop only when we already have image file/uri?

### ISSUE THREAD

**Issue by andj207** [Dhaval2404/ImagePicker#183]
User has an image file selected somewhere in my app, and now user just want to start cropping that image. What code should I use?

**Comment by sinhpn92** [comment]
I have same question about it. Did you solve it? @andj207

**Comment by andj207** [comment]
@sinhpn92 I don't know how with this lib, I decided to use the lib here https://github.com/ArthurHub/Android-Image-Cropper

**Comment by sinhpn92** [comment]
@andj207 Humzzz.
Thanks. I have used uCrop for my project. uCrop was used by this lib too.

**Comment by vcuk21** [comment]
@andj207 https://github.com/ArthurHub/Android-Image-Cropper is deprecated and @sinhpn92 ucrop has issues with Android 10/11

I'm using https://github.com/CanHub/Android-Image-Cropper that come from the one @andj207 said. And is maintaned.

**Comment by vcuk21** [comment]
> @vcuk21 I have tested uCrop on Android 11/ Samsung galaxy s10+ and emulator pixel 3 with android 10. It's working fine.

hmm, I saw many issues and this one: https://github.com/Yalantis/uCrop/issues/715
So I'm going for the one which is more maintained, but if works for you use, is an amazing lib!

**Comment by Dhaval2404** [comment]
@andj207 ImagePicker doesn't support crop-only feature. You can use uCrop library directly in your project.
