### ISSUE TITLE
Falied to create camera image file

### ISSUE THREAD

**Issue by Bharatsingh049** [Dhaval2404/ImagePicker#186]
The same issue persists with android 11. I have also tried the **requestLegacyExternalStorage** but it didn't seem to work.
Please help.

**Comment by HosseinKurd** [comment]
Same Issue `Failed to create crop image file`

On Android 10
Xiaomi Redmi Note 8

**Comment by Dhaval2404** [comment]
The issue has been resolved in v2.0.
