### ISSUE TITLE
How to get Selected Image as Bitmap?

### ISSUE THREAD

**Issue by Sid110307** [Dhaval2404/ImagePicker#190]
# SDK version
`com.github.dhaval2404:imagepicker:1.8`

![image](https://user-images.githubusercontent.com/67900745/114562186-e7e71380-9c8b-11eb-8fd9-b5721ed2639a.png)

**Comment by hashem-saqqa** [comment]
u can override the onActivityResult method and get the result there from the data 
    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK & data != null) {

            String file = ImagePicker.Companion.getFilePath(data);
            profileImage.setImageBitmap(BitmapFactory.decodeFile(file));

   }
}

**Comment by Dhaval2404** [comment]
Thank you @hashem-saqqa for the feedback. @Sid110307 hope your question is answered.

**Comment by Sid110307** [comment]
Thank you. I solved it by ```imageView.setImageBitmap(decodeStream(getContentResolver().openInputStream(data.getData())));```
