### ISSUE TITLE
Still maintained? 

### ISSUE THREAD

**Issue by vcuk21** [Dhaval2404/ImagePicker#196]
Will this library be update for Android 10 and 11 with the issues?
@Dhaval2404 still actively working on this? 

I see we have some important PRs from @GuilhE and @Drjacky for release 2.0.0 and 2.0.1 but they look blocked =(((

I found this other lib: https://github.com/CanHub/Android-Image-Cropper
But I don't wanna spent time changing if this one should be fixed soon =D

**Comment by vishalkumarsinghvi** [comment]
Hey @vcuk21, I sent mail to @Dhaval2404 but no update response till now so  I think we have to shift to another library

**Comment by vcuk21** [comment]
Ty for the update @vishalkumarsinghvi

**Comment by vishalkumarsinghvi** [comment]
If you update or change something let me know I will also update code @vcuk21

**Comment by vishalkumarsinghvi** [comment]
Have you got a warning from play console?

**Comment by Drjacky** [comment]
@vcuk21 & @vishalkumarsinghvi Please try this version and let me know if it works: [v2.0.4](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.4)

**Comment by vishalkumarsinghvi** [comment]
@Drjacky  In this library have you used read & write permission ?

**Comment by Drjacky** [comment]
@vishalkumarsinghvi Just `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

**Comment by vishalkumarsinghvi** [comment]
@Drjacky Have you restricted WRITE_EXTERNAL_STORAGE this permission for android SDK 28?

**Comment by Drjacky** [comment]
@vishalkumarsinghvi Please explain your concern a little bit more.

**Comment by vcuk21** [comment]
Thanks @Drjacky already using the Image Cropper. Maybe you should drop your fixes on it! they are updating the library always  and has more downloads than this one, but less stars 🤔

**Comment by vishalkumarsinghvi** [comment]
@vcuk21 @Drjacky  

I used this library github.com/Dhaval2404/ImagePicker and I got a warning from the android play console, team We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs. Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either: 

Right now till android 9, everything is fine with permission we can easily pick an image from the gallery if we have this permission READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE
android 10 for a temporary  fix I added requestLegacyExternalStorage="true" but after android 11 this flag will be ignored

I have lots of doubts for android 10,11 regarding permissions  and flag requestLegacyExternalStorage="true"
 - Is READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions are deprecated for android 10 and 11?
 -  requestLegacyExternalStorage="true" we have to use or not for
       android 10?
 -  If I want to pick an image for android devices show I need
       MANGAE_EXTERNAL_STORAGE permission or not?
 - I am not using this MANGAE_EXTERNAL_STORAGE permission but I am
       using requestLegacyExternalStorage="true" in manifest and my target
       SDK 29 so play store will take action after 5 May 2021 because I got
       a warning from the play console team?

**Comment by vishalkumarsinghvi** [comment]
@vcuk21 Which library is safe & we can use it.

**Comment by Drjacky** [comment]
@vishalkumarsinghvi Please look at the [URL](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.4) again. That's my library which uses the Dhaval repo as the base.

**Comment by Drjacky** [comment]
> - Is READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions are deprecated for android 10 and 11?

If scoped storage is enabled, the collection shows only the photos, videos, and audio files that your app has created. Most developers won't need to use MediaStore.Files to view media files from other apps, but if you have a specific requirement to do so, you can declare the READ_EXTERNAL_STORAGE permission. It's recommended, however, that you use the MediaStore APIs to open files that your app hasn't created.
If your app uses scoped storage, it should request storage-related permissions only for devices that run Android 9 (API level 28) or lower. You can apply this condition by adding the android:maxSdkVersion attribute to the permission declaration in your app's manifest file:

```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="28" />
```
Don't unnecessarily request storage-related permissions for devices that run Android 10 or higher. Your app can contribute to well-defined media collections, including the MediaStore.Downloads collection, without requesting any storage-related permissions. If you're developing a camera app, for example, you don't need to request storage-related permissions because your app owns the images that you're writing to the media store.

To access files that other apps have created, the following conditions must each be true:

Your app has been granted the READ_EXTERNAL_STORAGE permission.
The files reside in one of the following well-defined media collections:
MediaStore.Images
MediaStore.Video
MediaStore.Audio
Source: https://developer.android.com/training/data-storage/shared/media
____
> - requestLegacyExternalStorage="true" we have to use or not for
android 10?

If you target on Android 10 but, you run your app on Android 11, you still can use `requestLegacyExternalStorage` as a temporary solution.

____
> - If I want to pick an image for android devices show I need
MANGAE_EXTERNAL_STORAGE permission or not?

Do not use that flag at all unless your app is satisfying [Google Play Store policy](https://support.google.com/googleplay/android-developer/answer/10467955)

____
> - I am not using this MANGAE_EXTERNAL_STORAGE permission but I am
using requestLegacyExternalStorage="true" in manifest and my target
SDK 29 so play store will take action after 5 May 2021 because I got
a warning from the play console team?

No, `requestLegacyExternalStorage` and targeting Android 10 is safe from the action on 5 May, 2021.

**Comment by Drjacky** [comment]
@vcuk21 Thanks. yes, it's a well-coded library. I'll take a look into it and try to improve my code.

@vishalkumarsinghvi I'd suggest you use the suggestion [library](https://github.com/CanHub/Android-Image-Cropper) until Dhaval's library or [mine](https://github.com/Drjacky/ImagePicker) could fix the issue on API **29** regards picking an image from Gallery.

**Comment by vishalkumarsinghvi** [comment]
@Drjacky Thank you so much :)

**Comment by vishalkumarsinghvi** [comment]
> > - Is READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions are deprecated for android 10 and 11?
> 
> If scoped storage is enabled, the collection shows only the photos, videos, and audio files that your app has created. Most developers won't need to use MediaStore.Files to view media files from other apps, but if you have a specific requirement to do so, you can declare the READ_EXTERNAL_STORAGE permission. It's recommended, however, that you use the MediaStore APIs to open files that your app hasn't created.
> If your app uses scoped storage, it should request storage-related permissions only for devices that run Android 9 (API level 28) or lower. You can apply this condition by adding the android:maxSdkVersion attribute to the permission declaration in your app's manifest file:
> 
> ```xml
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
>                  android:maxSdkVersion="28" />
> ```
> Don't unnecessarily request storage-related permissions for devices that run Android 10 or higher. Your app can contribute to well-defined media collections, including the MediaStore.Downloads collection, without requesting any storage-related permissions. If you're developing a camera app, for example, you don't need to request storage-related permissions because your app owns the images that you're writing to the media store.
> 
> To access files that other apps have created, the following conditions must each be true:
> 
> Your app has been granted the READ_EXTERNAL_STORAGE permission.
> The files reside in one of the following well-defined media collections:
> MediaStore.Images
> MediaStore.Video
> MediaStore.Audio
> Source: https://developer.android.com/training/data-storage/shared/media
> ____
> > - requestLegacyExternalStorage="true" we have to use or not for
> android 10?
> 
> If you target on Android 10 but, you run your app on Android 11, you still can use `requestLegacyExternalStorage` as a temporary solution.
> 
> ____
> > - If I want to pick an image for android devices show I need
> MANGAE_EXTERNAL_STORAGE permission or not?
> 
> Do not use that flag at all unless your app is satisfying [Google Play Store policy](https://support.google.com/googleplay/android-developer/answer/10467955)
> 
> ____
> > - I am not using this MANGAE_EXTERNAL_STORAGE permission but I am
> using requestLegacyExternalStorage="true" in manifest and my target
> SDK 29 so play store will take action after 5 May 2021 because I got
> a warning from the play console team?
> 
> No, `requestLegacyExternalStorage` and targeting Android 10 is safe from the action on 5 May, 2021.

😊

**Comment by Drjacky** [comment]
@vishalkumarsinghvi The issue regards pick the image from Gallery in Api 29 has been fixed: [v2.0.5](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.5)

Now, the library works on API 19-30 without any problem.

**Comment by vishalkumarsinghvi** [comment]
> @vishalkumarsinghvi The issue regards pick the image from Gallery in Api 29 has been fixed: [v2.0.5](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.5)
> 
> Now, the library works on API 19-30 without any problem.

Your sample code is updated?.

**Comment by Drjacky** [comment]
@vishalkumarsinghvi

Yes: https://github.com/Drjacky/ImagePicker/tree/master/sample
Sample app and ImagePicker library use this line:
`versionName rootProject.ext.versionName`
which at this moment is:
```groovy
buildscript {
    ext {
        kotlin_version = '1.4.32'
        versionCode = 24
        versionName = '2.0.5'
    }
```

I've tested on API 28, 29, 30 by myself.
Feel free to test and return back to me [here](https://github.com/Drjacky/ImagePicker/issues) if you found an issue.

**Comment by vishalkumarsinghvi** [comment]
> @vishalkumarsinghvi
> 
> Yes: https://github.com/Drjacky/ImagePicker/tree/master/sample
> Sample app and ImagePicker library use this line:
> `versionName rootProject.ext.versionName`
> which at this moment is:
> ```groovy
> buildscript {
>     ext {
>         kotlin_version = '1.4.32'
>         versionCode = 24
>         versionName = '2.0.5'
>     }
> ```
> 
> I've tested on API 28, 29, 30 by myself.
> Feel free to test and return back to me [here](https://github.com/Drjacky/ImagePicker/issues) if you found an issue.

Sure I will test soon let you know 
Thank again for your code.

**Comment by vishalkumarsinghvi** [comment]
> @vishalkumarsinghvi Just `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`
> 
> ```kotlin
> /**
>          * Permission Require for Image Capture using Camera
>          */
>         private val REQUIRED_PERMISSIONS = arrayOf(
>             Manifest.permission.WRITE_EXTERNAL_STORAGE
>         )
> 
>         /**
>          * Permission Require for Image Capture using Camera
>          */
>         private val REQUIRED_PERMISSIONS_EXTENDED = arrayOf(
>             Manifest.permission.WRITE_EXTERNAL_STORAGE,
>             Manifest.permission.CAMERA
>         )
> /**
>          * Permission Require for Image Pick, For image pick just storage permission is need but
>          * to crop or compress image write permission is also required. as both permission is in
>          * same group, we have used write permission here.
>          */
>         private val REQUIRED_PERMISSIONS = arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE)
> ```

In your library Without WRITE_EXTERNAL_STORAGE Permission we can handle camera click or we have to add this permission in our manifest because in your sample code you did not mention it .

**Comment by vishalkumarsinghvi** [comment]
@Drjacky I tested on android 10 only the downloaded folder image is working fine, the media did not find an error when selecting a gallery image.

**Comment by Drjacky** [comment]
> In your library Without WRITE_EXTERNAL_STORAGE Permission we can handle camera click or we have to add this permission in our manifest because in your sample code you did not mention it .

Follow the sample app. The necessary permissions are there.
In other word: Do not add/no need to add `WRITE_EXTERNAL_STORAGE`.

____

> I tested on android 10 only the downloaded folder image is working fine, the media did not find an error when selecting a gallery image.

So, we're good, right? 🙂

**Comment by vishalkumarsinghvi** [comment]
No,@Drjacky If you select an image like recent or image directory app is showing a blank image and if you tap on image media not found toast will come.For android 10 only

**Comment by vcuk21** [comment]
Amazing work @Drjacky but now I'm using the other lib =/ (https://github.com/CanHub/Android-Image-Cropper) cause is working for every case

Hopefully they will let you be part of the maintainers \o/

**Comment by vishalkumarsinghvi** [comment]
@vcuk21 Above mentioned library moto is only for image cropping right?

**Comment by vcuk21** [comment]
> @vcuk21 Above mentioned library moto is only for image cropping right?

What you mean by "moto"??

The lib has camera, gallery, doc picker and image cropper, rotation, oval crop, custom layout and activity extended options.

**Comment by vishalkumarsinghvi** [comment]
Okay, Thanks @vcuk21  I thought this library is only used for cropping images.

**Comment by Drjacky** [comment]
ℹ️ For anyone who got here, [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) works perfectly on APIs 19-30. ℹ️
