### ISSUE TITLE
Update required!! Won't be supported by playstore if not resolved.

### ISSUE THREAD

**Issue by CatalystMonish** [Dhaval2404/ImagePicker#199]
One of my app uses this Image Picker and recently google send this out, hence applications may get removed from the playstore, please help!

![114824531-a5841a80-9de2-11eb-9723-c17556d4cb75](https://user-images.githubusercontent.com/30138405/117538580-76994700-b024-11eb-9cb6-5402089f5b45.png)

**Comment by piotr-andrychiewicz-spaceos** [comment]
I wrote to @Dhaval2404 about this issue few weeks ago, he tole he will fix it, however as far as I know no action were taken. It's sad. Today I switch to other library

**Comment by CatalystMonish** [comment]
> @CatalystMonish @piotr-andrychiewicz-spaceos Have a look at this library https://github.com/Drjacky/ImagePicker

Thanks dude, did he solve the issue in it?

**Comment by CatalystMonish** [comment]
> I wrote to @Dhaval2404 about this issue few weeks ago, he told me he will fix it, however as far as I know no action were taken. It's sad. Today I switch to other library

Do you have any good library suggestions ?

**Comment by vishalkumarsinghvi** [comment]
> > @CatalystMonish @piotr-andrychiewicz-spaceos Have a look at this library https://github.com/Drjacky/ImagePicker
> 
> Thanks dude, did he solve the issue in it?

Yes, he resolved issue for all version

**Comment by vishalkumarsinghvi** [comment]
it's working fine in  android 10,11 i tested Right now I am targeting android 29 so I did not change anything but soon I will use this library @CatalystMonish

**Comment by hasansidd** [comment]
@Dhaval2404, are there plans to release a version with support for targetSDK 30? If not this library will be impossible to use in production now. If you have a rough timeline that would be great, but I know its free and open source so if you are too busy please let us know as well so we can commit to other options

**Comment by rahat14** [comment]
@Dhaval2404 please give us a feed back of u r plan we have in production using this library

**Comment by rahat14** [comment]
> I wrote to @Dhaval2404 about this issue few weeks ago, he told me he will fix it, however as far as I know no action were taken. It's sad. Today I switch to other library

which library

**Comment by instalogist** [comment]
> I wrote to @Dhaval2404 about this issue few weeks ago, he told me he will fix it, however as far as I know no action were taken. It's sad. Today I switch to other library

Please suggest which is you are using now, i also found this library quite buggy

**Comment by vcuk21** [comment]
> > I wrote to @Dhaval2404 about this issue few weeks ago, he told me he will fix it, however as far as I know no action were taken. It's sad. Today I switch to other library
> 
> Please suggest which is you are using now, i also found this library quite buggy

@rahat14 @instalogist 

another option https://github.com/CanHub/Android-Image-Cropper

**Comment by sagarbhojaviya** [comment]
@Dhaval2404 please give us a feedback of your plan for android 11 support or not so we can move to another library

**Comment by CatalystMonish** [comment]
Dhaval's status says he is out sick, that may be the reason he is not releasing updates!

**Comment by Dhaval2404** [comment]
Sorry for the delay! New release coming by end of the day!

**Comment by sagarbhojaviya** [comment]
thanks bro

**Comment by instalogist** [comment]
Latest release is breaking when i try to upload image from gallery

**Comment by Dhaval2404** [comment]
@instalogist The breaking changes are introduced to better support Android scope storage. 

You may find the below link useful to upload images using Uri. Let me know If I can be of any help.

https://commonsware.com/blog/2020/07/05/multipart-upload-okttp-uri.html

**Comment by vishalkumarsinghvi** [comment]
@Dhaval2404 in manifest of library android:requestLegacyExternalStorage=true  still exist 
 https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/AndroidManifest.xml

**Comment by Dhaval2404** [comment]
@vishalkumarsinghvi Thank you @vishalkumarsinghvi for bringing it to my notice. Will release a new version by end of the day.

**Comment by vishalkumarsinghvi** [comment]
> Thank you @vishalkumarsinghvi for bringing it to my notice. Will release a new version by end of the day.

I have one question right now we are not using any storage permission in this library?

**Comment by Dhaval2404** [comment]
@vishalkumarsinghvi No, ImagePicker does not require any storage permission to function.

**Comment by vishalkumarsinghvi** [comment]
> Thank you @vishalkumarsinghvi for bringing it to my notice. Will release a new version by end of the day.

Have you released any new build with above-mentioned issue

**Comment by Dhaval2404** [comment]
@vishalkumarsinghvi Sorry for the delay. The new version is released now. Please give it a try.
