### ISSUE TITLE
Failed to resolve: com.github.yalantis:ucrop:2.2.2

### ISSUE THREAD

**Issue by dev-myatminsoe** [Dhaval2404/ImagePicker#2]
I think the ucrop dependencies is 'com.yalantis:ucrop:2.2.0-native'

**Comment by dev-myatminsoe** [comment]
If someone is also having a problem, you can use like this for now.

```
implementation ('com.github.dhaval2404:imagepicker:1.0'){
     exclude group: 'com.github.yalantis', module: 'ucrop'
}
implementation 'com.yalantis:ucrop:2.2.0-native'
```

**Comment by Dhaval2404** [comment]
@dev-myatminsoe Thank you very much for the feedback.  

You need to add jitpack repository in your build.gradle

```
allprojects {
    repositories {
         jcenter()
         maven { url "https://jitpack.io" }  //Make sure to add this in your project for uCrop
    }
}

```
Regarding which uCrop lib to use:

For lightweight general solution
`implementation  'com.github.yalantis:ucrop:2.2.2`

To get the power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
`implementation  'com.github.yalantis:ucrop:2.2.2-native'`

So, Developer can use the ucrop lib as per there use-cases. Will Include the same in readme file as well.

Thank you!
