### ISSUE TITLE
How to save img path/name

### ISSUE THREAD

**Issue by LyamD** [Dhaval2404/ImagePicker#20]
Hi, the title is pretty self explanatory :

I got a local database and I want to get the the full path (name of the pic included) in a String to save it.

**Comment by Dhaval2404** [comment]
@LyamD Looks like you already figure out the way. But if you still have a problem please check out the sample code from below link(Specially onActivityResult method):

https://github.com/Dhaval2404/ImagePicker/blob/master/sample/src/main/kotlin/com.github.dhaval2404.imagepicker/sample/MainActivity.kt

**Comment by LyamD** [comment]
Yeah I just read the doc and see that there are a way to get the path String. I"ll play around with it to see if it's really what I need or if I need to make add some code myself.

Thank's for the response anyway

**Comment by LyamD** [comment]
Okay one last question, is there a way to change the path of where the image is stored ? or do I need to save it myself where I want to ?

**Comment by Dhaval2404** [comment]
@LyamD Changing the path of the image is not supported now. I add this feature in the upcoming release.
Thanks for the suggestion.
