### ISSUE TITLE
Cannot resolve method 'getFile' in 'ImagePicker'

### ISSUE THREAD

**Issue by phath9** [Dhaval2404/ImagePicker#201]
getFile method seems to be missing from ImagePicker. I've followed the instructions in the README to get Uri but getFile is not working.

`ImagePicker.getFile(data)`

**Comment by Dhaval2404** [comment]
If you're using Java then try. 

  ```java
ImagePicker.Companion.getFile(data)
```

Note: This method will be removed in v2.0. Use Uri object instead of File to compatibility with Android 11 Scope Storage.
