### ISSUE TITLE
How to get the File from uri got in ActivityResult?

### ISSUE THREAD

**Issue by nishu3389** [Dhaval2404/ImagePicker#202]
i am getting the uri in ActivityResult,
is there any way to get the file or file path above android 10?

Also getting rotated image when capturing from camera, any solution of this?

**Comment by Dhaval2404** [comment]
@nishu3389 Why do you need a File from Uri? If you need it for file upload, Let me know which library you are using so I will suggest appropriate solutions for the same. My recommendation is to use Uri to better support scope storage.

The possible solution is to copy Uri to an app-specific folder and access it using the File object. But why should we do extra processing when things can be done using Uri.

**Comment by daryljodanny** [comment]
@Dhaval2404 Will using the extension function in core-ktx do the trick in converting the Uri to File? I'm looking to upload the file via retrofit

**Comment by Dhaval2404** [comment]
You must have created RequestBody from the File object before uploading using a retrofit.


Previous implementation:

```kotlin
val fileBody = file.asRequestBody(getMimeType(file).toMediaTypeOrNull())
val params = HashMap<String, RequestBody>()
// file = your image upload field name
params["file\"; filename=\"${file.name}\""] =  fileBody
```

Here is the minor change into that:

```kotlin
val fileName = InputStreamRequestBody.getFileName(context, uri)
val params = HashMap<String, RequestBody>()
// file = your image upload field name
params["file\"; filename=\"${fileName}\""] =  InputStreamRequestBody(context, uri) 
```

You can find the **InputStreamRequestBody** class from the below link:
https://gist.github.com/Dhaval2404/f73442b8e584beb9243b465d7b22e2fa

Let me know if you have any trouble implementing this solution.

**Comment by nishu3389** [comment]
"The possible solution is to copy Uri to an app-specific folder and access it using the File object. But why should we do extra processing when things can be done using Uri."

it will be great if you implement this process into your library in case we really need the file object.

Thanks :)
