### ISSUE TITLE
Not working into Android 11

### ISSUE THREAD

**Issue by rrsaikat** [Dhaval2404/ImagePicker#206]
Library works well for smaller android versions like 10, 9, 8, 8.1 (tested) but not working into android 11.

Scenario:
When i call `ImagePicker.with(this).start()` nothings happens.

Device: One Plus 6
OS: Android 11

**Comment by Dhaval2404** [comment]
@rrsaikat What is the ImagePicker version you tested on?

**Comment by Dhaval2404** [comment]
@rrsaikat Can you please provide info ImagePicker version you used?

**Comment by Azarnoyz** [comment]
I tried on Android 11, all works

**Comment by untungsujarwo** [comment]
is the support build artifact hasn't support Android 11 ?

**Comment by vishalkumarsinghvi** [comment]
Thanks to @Dhaval2404.
I Finished the new version 2.1 and it's working fine 
Help resource [](https://gist.github.com/Dhaval2404/f73442b8e584beb9243b465d7b22e2fa) if you have problem with multipart body

**Comment by rahat14** [comment]
working fine in android 11
