### ISSUE TITLE
There is a dialog that blink after success in camera only mode

### ISSUE THREAD

**Issue by antranvn** [Dhaval2404/ImagePicker#208]
## Summary

There is a dialog that blink after success in camera only mode
## Code to reproduce

I just use sample source code
## Android version

SDK 29
## Impacted devices

vsmart Joy3
## SDK version

SDK 29
## Other information

You can see recorded screen for reference. How can I remove that dialog blink?
https://drive.google.com/file/d/1gdH2akEcNVR4uh_gk6BaeBEo79UHXsPk/view?usp=sharing

**Comment by Dhaval2404** [comment]
There is no progress dialog in the ImagePicker library, So this must be coming from the in-built camera app. Please let me know your thoughts.

![image](https://user-images.githubusercontent.com/7314181/120057477-06994200-c061-11eb-90c8-4adeabfa659e.png)

**Comment by antranvn** [comment]
You are right, it is issue of in-built camera app. So we should close this issue. I need to develop camera preview using CameraX my-self to handle this issue ~~.
