### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by petezajot** [Dhaval2404/ImagePicker#21]
How can i change the language or the text in the labels in the alert dialog?

**Comment by Dhaval2404** [comment]
@petezajot It supports English only for now.

**Comment by petezajot** [comment]
Can i use custom text?

**Comment by Dhaval2404** [comment]
@petezajot No. But if you want to add language just duplicate below file in your language specific folder and change the text.
https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/res/values/strings.xml

Also If you want to change text Refer: [#17 ](https://github.com/Dhaval2404/ImagePicker/issues/17)

**Comment by petezajot** [comment]
it worked perfect! Thank you!

**Comment by nguyenhunq221** [comment]
> @petezajot No. But if you want to add language just duplicate below file in your language specific folder and change the text. https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/res/values/strings.xml
> 
> Also If you want to change text Refer: [#17 ](https://github.com/Dhaval2404/ImagePicker/issues/17)

how can i repalce icon in dialog? thank u @Dhaval2404
