### ISSUE TITLE
Cancel Listener

### ISSUE THREAD

**Issue by Azarnoyz** [Dhaval2404/ImagePicker#211]
Hi, I am using your library in webview and there when the cancel button is clicked, I need to send onReceiveValue() but I can't listen it, could you add a cancel button listener? I know that there is a setDismissListener, but it works every time the dialog disappears, I need it exactly when the button cancel is pressed. Thank you.

**Comment by Dhaval2404** [comment]
Hi @Azarnoyz, The Cancel Listener is not available in ImagePicker. The alternate way is to use your custom dialog instead of ImagePicker (Bonus: You can use dialog code from ImagePicker) and show ImagePicker with selected provider. 

```kotlin
/**
 * Show Image Provide Picker Dialog. Customize it as per your need
 */
fun showChooseAppDialog(
    activity: FragmentActivity, listener: (ImageProvider) -> Unit
) {
    val layoutInflater = LayoutInflater.from(activity)
    val customView = layoutInflater.inflate(R.layout.dialog_choose_app, null)

    //Add Cancel Listener on AlertDialog and handle it as per your need
    val dialog = AlertDialog.Builder(activity)
        .setTitle(R.string.title_choose_image_provider)
        .setView(customView)
        .show()

    // Handle Camera option click
    customView.findViewById<View>(R.id.lytCameraPick).setOnClickListener {
        listener.invoke(ImageProvider.CAMERA)
        dialog.dismiss()
    }

    // Handle Gallery option click
    customView.findViewById<View>(R.id.lytGalleryPick).setOnClickListener {
        listener.invoke(ImageProvider.GALLERY)
        dialog.dismiss()
    }
}
```

Usage:
```kotlin
showChooseAppDialog(this) { provider->
    ImagePicker.with(this)
        .provider(provider)
        .start()
}

**Comment by thilak310** [comment]
Can anyone help me with java equivalent code of above kotlin code? thanks in advance
