### ISSUE TITLE
Permission handling in playstore

### ISSUE THREAD

**Issue by sitamadex11** [Dhaval2404/ImagePicker#222]
Actually, I am developing an e-commerce application using this great library. I want to upload my app to the play store. Then should I mention the permissions (camera and storage) in my play console as the library is handling the permissions automatically?
I have not any experience with the play console, please help me.

**Comment by rahat14** [comment]
no need .

**Comment by Dhaval2404** [comment]
@sitamadex11 ImagePicker doesn't require any permission so you won't face any issue with the google play store.
