### ISSUE TITLE
URI to file path in java getting error

### ISSUE THREAD

**Issue by appukrb** [Dhaval2404/ImagePicker#224]
I am using V2.1, In Return URI looks like below, But **setImageUri**() working fine for the below URI. 
`ActivityResult{resultCode=RESULT_OK, data=Intent { dat=content://com.android.providers.downloads.documents/document/376 (has extras) }}`

I can't able to covert the URI to File getting Invalid URI exception

> new File(new URI(data.getData().getPath());

java.lang.IllegalArgumentException: Invalid URI: content://com.android.providers.downloads.documents/document/376

**Comment by Rakesh-Card91** [comment]
same here

**Comment by Rakesh-Card91** [comment]
> I am using V2.1, In Return URI looks like below, But **setImageUri**() working fine for the below URI.
> `ActivityResult{resultCode=RESULT_OK, data=Intent { dat=content://com.android.providers.downloads.documents/document/376 (has extras) }}`
> 
> I can't able to covert the URI to File getting Invalid URI exception
> 
> > new File(new URI(data.getData().getPath());
> 
> java.lang.IllegalArgumentException: Invalid URI: content://com.android.providers.downloads.documents/document/376

Use this `FileUtil.getFileInfo(requireContext(),fileUri)` to get path

**Comment by appukrb** [comment]
wrongly parse the URI, working fine

**Comment by appukrb** [comment]
@Rakesh-Card91  how to achieve in java **FileUtil.getFileInfo(requireContext(),fileUri)**

**Comment by appukrb** [comment]
thanks @Rakesh-Card91  got it `FileUtil.INSTANCE.getTempFile(getActivity(),result.getData().getData());`

**Comment by Dhaval2404** [comment]
**Do not parse URI to file, It will not work**(Even you get the path there will be a permission issue).

There will be an alternate way to achieve the same with uri which you're trying to achieve with the file object.

**Comment by egeysn** [comment]
File file = new File(Objects.requireNonNull(FileUriUtils.INSTANCE.getRealPath(OrderReviewActivity.this, uri))); 
its working me perfectly
