### ISSUE TITLE
Circle crop

### ISSUE THREAD

**Issue by eldon97** [Dhaval2404/ImagePicker#235]
there is already square crop. it will be nice to have circle crop for use case like profile picture..

**Comment by hitesh-dhamshaniya** [comment]
You can achieve it by circle transformation. 
If you are used Glide v4 below code snippets would work for you.
 ```
 Glide.with(context)
        .load(url)
        .circleCrop()
        .into(imageView);
```
if you are used Picasso below code snippets would work for you
```
implementation 'jp.wasabeef:picasso-transformations:2.2.1'
Picasso.with(context)
       .load(url)
       .resize(w, h)
       .transform(new CropCircleTransformation())
       .into(imageview);
```

**Comment by Dhaval2404** [comment]
@eldon97 As of now circle crop is not supported but you can go with the approach specified by @hitesh-dhamshaniya above.

You can find the same to be implemented in the sample code. Also, check Profile Image Picker in the preview section for demo.
