### ISSUE TITLE
App name should be removed from library project

### ISSUE THREAD

**Issue by HimanshuDudhat** [Dhaval2404/ImagePicker#236]
## Summary
Adding library to the project changing the app name as most of the app having app_name key default.

## Code to reproduce
- Just add image picker library in dependency  

## Android version
ALL

## Impacted devices
All

## SDK version
2.1

**Comment by Dhaval2404** [comment]
Thank you @HimanshuDudhat for the suggestion. 

The changes will be reflected in the next release.
