### ISSUE TITLE
Delete Selected Image

### ISSUE THREAD

**Issue by wishstore36** [Dhaval2404/ImagePicker#239]
Thanks for the Library.

there is requirement to delete the Selected Image, can you please guide how to achieve the same.

Once the client has selected image, other processing is done in the app, and moment the data is saved, the selected image must be deleted.

**Comment by Dhaval2404** [comment]
@wishstore36  Specify the Image Save Directory and delete the image in it after the image procession is done.

Please check the readme file to know more about the save directory.
