### ISSUE TITLE
Save Image to Byte Array/Bitmap

### ISSUE THREAD

**Issue by Sid110307** [Dhaval2404/ImagePicker#244]
I'm looking for a way to save the picked image to a variable such as a byte array or a bitmap. How can I do so?

I have tried this:
```java
public byte[] getBytes(InputStream inputStream) {
      ByteArrayOutputStream byteBuffer = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];

      try {
          int length = 0;
          while ((length = inputStream.read(buffer)) != -1)
                byteBuffer.write(buffer, 0, length);
          return byteBuffer.toByteArray();
      } catch (IOException e) { e.printStackTrace(); }
}
```
but it returns a black image when converted to an image:
<img src="https://user-images.githubusercontent.com/67900745/132236672-e9eda21b-a178-4b84-8db8-2ee2b345474d.png">

**Comment by Dhaval2404** [comment]
@Sid110307 I think this link will help you. [https://stackoverflow.com/questions/10296734/image-uri-to-bytesarray](https://stackoverflow.com/questions/10296734/image-uri-to-bytesarray)

**Comment by Sid110307** [comment]
Thanks for the quick response. I have tried it, but it returns a black image when converted to an image:
<img src="https://user-images.githubusercontent.com/67900745/132236672-e9eda21b-a178-4b84-8db8-2ee2b345474d.png">
