### ISSUE TITLE
Could not find com.github.yalantis:ucrop:2.2.2 again

### ISSUE THREAD

**Issue by harloom** [Dhaval2404/ImagePicker#25]
Could not find com.github.yalantis:ucrop:2.2.2.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.2/ucrop-2.2.2.pom
  - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.2/ucrop-2.2.2.jar
  - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.2/ucrop-2.2.2.pom
  - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.2/ucrop-2.2.2.jar
Required by:
    project :app > com.github.dhaval2404:imagepicker:1.3

my gradle
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }

    }

i am url   - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.2/ucrop-2.2.2.jar
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

please update

**Comment by Dhaval2404** [comment]
@harloom Strange! Looking into it now.

**Comment by harloom** [comment]
iam sory ,because i dizzy today
