### ISSUE TITLE
onActivityResult  now deprecated

### ISSUE THREAD

**Issue by mohammedmans** [Dhaval2404/ImagePicker#271]
Hello,
I'm trying implement in java using registerForActivityResult because onActivityResult now is deprecated,
but can't call 
```
createIntent { intent ->
            startForProfileImageResult.launch(intent)
        }
```

**Comment by wiryadev** [comment]
Try to implement the latest activity and fragment dependencies

**Comment by mohammedmans** [comment]
Thanks, Worked.
