### ISSUE TITLE
when i open camera app crashes

### ISSUE THREAD

**Issue by ArunkumarAdhash** [Dhaval2404/ImagePicker#28]

**Comment by Dhaval2404** [comment]
Can you please provide me below info:
1. ImagePicker Version
2. Device Info
3. Device Android OS

**Comment by Dhaval2404** [comment]
@ArunkumarAdhash Can you please help me out here. Any crash log will be great to help.

Thank you!

**Comment by Dhaval2404** [comment]
@ArunkumarAdhash Do you have any crash logs? That would be a great help.

Thank you!
