### ISSUE TITLE
does it work for fragment

### ISSUE THREAD

**Issue by FreedomChuks** [Dhaval2404/ImagePicker#31]
it always giving me task cancelled i overided onActivityResult

**Comment by Dhaval2404** [comment]
@gzodx Can see any error or warning in logcat?  

Any help to reproduce the issue will be appreciated.

**Comment by hmeragon** [comment]
If you want to use this in Fragment, instead of use GetActivity(), use YourFragmentName.this
```
ImagePicker.Companion.with(TimelineFragment.this)
                                        .cropSquare()
                                        .start(PICK_IMAGE_AVATAR);
```
