### ISSUE TITLE
Get Image form gallery not work in andorid Q

### ISSUE THREAD

**Issue by ngoluuduythai** [Dhaval2404/ImagePicker#35]
https://developer.android.com/training/data-storage/files/external-scoped <br/>
Warning: Apps will be required to use scoped storage in next year's major platform release for all apps, independent of target SDK level. Therefore, you should ensure that your app works with scoped storage well in advance. To do so, make sure that the behavior is enabled for devices that run Android 10 (API level 29) and higher. <br/>
I add this to manifest and everything work perfect.
`<manifest ... >
  
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>`

**Comment by angelkoh** [comment]
note that requestLegacyExternalStorage will be removed in Android 11.
you will need to go through stored media API to access images.
