### ISSUE TITLE
Dynamically  choose crop ratio 

### ISSUE THREAD

**Issue by Dor-Sloim** [Dhaval2404/ImagePicker#36]
Is there an option to let your users choose crop ratio dynamically?
If not, could you add one using the [https://github.com/Yalantis/uCrop](url) library?

**Comment by Dhaval2404** [comment]
@Dor-Sloim Sorry, I didn't get your exact requirement. uCrop is already added in this lib. Currently, you can pass crop ration as below:

``` kotlin
ImagePicker.with(this)
	.crop(16f, 9f)	//Crop image with 16:9 aspect ratio
	.start()
```

Here, the Crop option is optional.

**Comment by Dor-Sloim** [comment]
I want to be able to do:
`ImagePicker.with(this)
	.**crop()**	
	.start()`
Then, when the user crops, **he** can change the aspect ratio.

**Comment by Dhaval2404** [comment]
@Dor-Sloim I will try to integrate the feature in the next few hours.

Thank you so much for the feedback.

**Comment by Dor-Sloim** [comment]
Thank you so much !
This might help you:

> If you want to let your users choose crop ratio dynamically, just do not call withAspectRatio(x, y).

**Comment by Dor-Sloim** [comment]
Great.
When do you think you will release 

> implementation 'com.github.dhaval2404:imagepicker:**1.5**'

I'l be more than happy to test it and let you know if i find any bugs.
And again, Thank you so much !

**Comment by Dhaval2404** [comment]
@Dor-Sloim Can you please check out the latest lib.
