### ISSUE TITLE
Failed to create Camera image file !

### ISSUE THREAD

**Issue by vthakkar66** [Dhaval2404/ImagePicker#38]
Hello i am getting Failed to create Camera image file in Error. !
device : PIXEL 3A  API 29 Android Q
targetSdkVersion:29

Suggestion:

1. You can not get public directory at API 29 LEVEL.. it is deprecated..

 private fun getCameraDirectory(): File {
        val dir = context.getExternalFilesDir(null)!!.absolutePath
        return File(dir, "Camera")
    }

2.  Change the targetSdkVersion to 28 from build.gradle file.

**Comment by Dhaval2404** [comment]
@vthakkar66 Sorry for the late reply. I was on Diwali vacation😊

Have you tried to set ```android:requestLegacyExternalStorage="true"``` in android manifest. It's a must for API 29.

![image](https://user-images.githubusercontent.com/7314181/68088859-1bafee00-fe89-11e9-81eb-e17b0d823bfc.png)

**Comment by vthakkar66** [comment]
> @vthakkar66 Sorry for the late reply. I was on Diwali vacation
> 
> Have you tried to set `android:requestLegacyExternalStorage="true"` in android manifest. It's a must for API 29.
> 
> ![image](https://user-images.githubusercontent.com/7314181/68088859-1bafee00-fe89-11e9-81eb-e17b0d823bfc.png)

Yupp.. it will wotk

**Comment by Bharatsingh049** [comment]
The same issue persists with android 11. I have also tried the **requestLegacyExternalStorage** but it didn't seem to work.
Please help.
