### ISSUE TITLE
Crop error after take pitcure

### ISSUE THREAD

**Issue by harloom** [Dhaval2404/ImagePicker#39]

**Comment by Dhaval2404** [comment]
@harloom Can you please provide some more info. Maybe some code, please?

**Comment by harloom** [comment]
`private fun loadImageFromCammera(){
        ImagePicker.with(this@CreateThreadFragment)
            .cameraOnly()    //User can only select image from Gallery
            .cropSquare()
            .compress(1024)
            .start(REQUEST_CODE_CAMERA)
    }`

ActivityonResult in fragment

`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_CODE_IMAGE && resultCode == RESULT_OK) {
            Log.d("Matisseiilham", "Uris: " + Matisse.obtainResult(data));
            Log.d("Matisseiilham", "Paths: " + Matisse.obtainPathResult(data));
            mSelected = Matisse.obtainPathResult(data)
            adapterI.submitList(mSelected)
            rcv_foto.adapter = adapterI
            destroyVideo()
        } else if (requestCode == REQUEST_CODE_VIDEO && resultCode == Activity.RESULT_OK) {
            Log.d("MatisseiVideo", "Uris: " + Matisse.obtainResult(data));
            Log.d("MatisseiVideo", "Paths: " + Matisse.obtainPathResult(data))
            startTrimActivity(Matisse.obtainResult(data)[0])
        } else if (requestCode == REQUEST_CODE_RESULT_TRIM && resultCode == Activity.RESULT_OK) {
            Log.d("TriMVideo", "Uri: " + data?.extras!!["returnUri"])
            val uri  = data.extras!!["returnUri"] as Uri
            initVideo(uri)
        }else if ( requestCode == REQUEST_CODE_CAMERA && resultCode == RESULT_OK){
            val filePath:String = ImagePicker.getFilePath(data).toString()
            mSelected.add(filePath)
            adapterI.submitList(mSelected)
            rcv_foto.adapter = adapterI
        }
    }`


Project base

https://github.com/harloom/JariManisV3/blob/2c18817f288133faf0b053571a2de477dc3d37ea/app/src/main/java/com/app/jarimanis/ui/thread/post/CreateThreadFragment.kt

Sorry Ian change library from take picture

**Comment by Dhaval2404** [comment]
@harloom Thank you so much for the feedback.

I have looked into your code and found that your app ```targetSdkVersion``` is 29, So you need to set ```android:requestLegacyExternalStorage="true"``` in android manifest. It's a must for API 29.

![image](https://user-images.githubusercontent.com/7314181/68139181-b7a42d00-ff4f-11e9-927a-eab7c7cf577f.png)

**Missing requestLegacyExternalStorage Option:**

![image](https://user-images.githubusercontent.com/7314181/68139220-c985d000-ff4f-11e9-8172-c309a971e795.png)

**As I mentioned in README file, Please set requestLegacyExternalStorage to true**

![image](https://user-images.githubusercontent.com/7314181/68139369-04880380-ff50-11e9-998d-e89bb2b11d16.png)

Hope this works for you.

**Comment by Dhaval2404** [comment]
@harloom does above solution works for you? Please reply so that I can close the issue.
Thanks
