### ISSUE TITLE
error: cannot access Function2 class file for kotlin.jvm.functions.Function2 not found

### ISSUE THREAD

**Issue by DevyankShaw** [Dhaval2404/ImagePicker#40]
It seems that result code doesn't work in Java. Kindly add this function for Java also.

**Comment by Dhaval2404** [comment]
It seems working fine with the below code:

![carbon](https://user-images.githubusercontent.com/7314181/71840707-e079a780-30e3-11ea-8a11-6193225e4e89.png)

**Comment by programmergauravgupta** [comment]
Getting Error "Cannot Resolve Symbol Unit"

**Comment by Dhaval2404** [comment]
Try below import

```kotlin
import kotlin.Unit;
import kotlin.jvm.functions.Function2;
```

**Comment by nobyali** [comment]
> Try below import
> 
> ```kotlin
> import kotlin.Unit;
> import kotlin.jvm.functions.Function2;
> ```

I cant import  these into java...sir please help. .i am fresher

**Comment by Dinosane2** [comment]
https://github.com/kyonifer/koma/issues/98 was the solution:

The classes it can't find are parts of the Kotlin standard library. Since you're not using Kotlin, you'll need to adjust your project's dependencies to include the kotlin standard library manually. If you're using gradle, that looks something like this:

repositories {
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:1.3.21"
}

**Comment by Hardikjain1207** [comment]
> [kyonifer/koma#98](https://github.com/kyonifer/koma/issues/98) was the solution:
> 
> The classes it can't find are parts of the Kotlin standard library. Since you're not using Kotlin, you'll need to adjust your project's dependencies to include the kotlin standard library manually. If you're using gradle, that looks something like this:
> 
> repositories { mavenCentral() }
> 
> dependencies { compile "org.jetbrains.kotlin:kotlin-stdlib:1.3.21" }

WORKS!
