### ISSUE TITLE
Camera opens twice when "Don't keep activities" option is ON

### ISSUE THREAD

**Issue by benji101** [Dhaval2404/ImagePicker#41]
Doing some tests while having the developer option "Don't keep activities" turned on (that simulates what could happen when low on memory). After taking a picture, the camera is started again. Taking a second picture, it now behave like it should. Please note that I'm using the cameraOnly() option.

I think the problem is that ImagePickerActivity, in its onCreate method, is not considering the savedInstanceState Bundle (which is not null if the activity has been destroyed and is being re-created). What I'm not sure is why it's working the second time, and not going on a loop.

Anyone else has this problem or can reproduce it?

**Comment by Dhaval2404** [comment]
@benji101 I'm able to reproduce the issue. I will try to fix this issue asap.
Thank you so much for the feedback.

**Comment by benji101** [comment]
@Dhaval2404 Thanks to you! I would have try to fix it myself, but I'm really busy at the moment, and I don't know Kotlin yet :(
Thanks for all the efforts you put in helping the community!

**Comment by kanczler** [comment]
Greetings! The camera still opens twice for me (only on my physical device, on emulators it's all right). Is there anything I could provide to help track down the issue?

**Comment by farmazon3000** [comment]
I'm having [similar but completely different issue](https://github.com/osmdroid/osmdroid/issues/1549) - when "don't keep activities" is enabled, custom view's ```onDetach``` is called twice, maybe you have the same?
