### ISSUE TITLE
it auto save every image when uploaded how can i stop this

### ISSUE THREAD

**Issue by gzodx** [Dhaval2404/ImagePicker#46]

**Comment by Dhaval2404** [comment]
@gzodx Do you mean upload on the server? Can you please explain the issue in detail?

**Comment by gzodx** [comment]
Both serve or just to display to my image view or any of that sort it saves a new copy on my mobile

**Comment by Dhaval2404** [comment]
@gzodx It seems like your making uploading webservice call on onActivityResult method. Can you show some code please?

**Comment by Dhaval2404** [comment]
> it saves a new copy on my mobile

Only when it process image. i.e. compress or crop image. if you disable both thing it will not create copy.

**Comment by gzodx** [comment]
yea definitely i am uploading to a web-service in this project onActivityResult

**Comment by gzodx** [comment]
ok thanks
wow so i cant have those features and still keep same copy? any work around?

**Comment by Dhaval2404** [comment]
Try Simple ```ImagePicker.with(this).start()``` will not create new image.

**Comment by gzodx** [comment]
Alight Thanks Soo much for your qucik response
