### ISSUE TITLE
Saving images to a particular path

### ISSUE THREAD

**Issue by ShankyPatel** [Dhaval2404/ImagePicker#50]
Hi how do i save images to a particular path upon saving ?

**Comment by Dhaval2404** [comment]
@ShankyPatel That's not supported in the current version. I will add support in the upcoming release.

**Comment by ShankyPatel** [comment]
Please do provide this functionality as you're already saving it so its better we could customise the path to save it to particular destination. Waiting for next release

**Comment by Dhaval2404** [comment]
#52
