### ISSUE TITLE
Silent Failure to Pick - ClassNotFound vs ClassCast and AppCompatActivity

### ISSUE THREAD

**Issue by jbienz** [Dhaval2404/ImagePicker#57]
In **ImagePicker.kt** **startActivity**, around line 299, there is the following code:

`if (e is ClassNotFoundException) {`

However, running Kotlin 1.3.61 and Java 1.8 the excption caught here is not a `ClassNotFoundException` it's a `ClassCastException`.

Because there is no other test for any other exception type in this handler, this method fails silently. To the developer, it appears that the picker fails without running the inline result handler.

Also, in the **READ.ME** it says:

> If you are yet to Migrate on AndroidX, Use support build artifact: `imagepicker-support:1.5`

I am using several AndroidX components, however I had not yet migrated my Activity to **AppCompatActivity**. (I'm actually writing a Tasker plugin and the Tasker sample library doesn't use that super class). Even after changing to use `imagepicker-support:1.5`, it appears the library still does a cast to **AppCompatActivity**.

I'm a bit unclear what support:1.5 is supposed to change if the library still depends on **AppCompatActivity**. If **AppCompatActivity** is in fact a requirement, please consider updating the **READ.ME** to make this requirement clear.

Thanks!

**Comment by Dhaval2404** [comment]
@jbienz  Thanks for pointing out the issue:

Currently, ImagePicker uses [InlineActivityResult](https://github.com/florent37/InlineActivityResult) to receive the activity result directly after the startActivityForResult. But as of now, [it doesn't work with Activity](https://github.com/florent37/InlineActivityResult/issues/3). I will mention this in READ.ME.

Also, ```imagepicker-support``` is built with the Android Support Library class. It's the same as ```imagepicker``` only difference is imagepicker-support use android support libs while imagepicker use Androidx.
