### ISSUE TITLE
Unable to change color/icon of camera and gallery of selection dialog 

### ISSUE THREAD

**Issue by pankajgurjar747** [Dhaval2404/ImagePicker#59]
As i need to change the color or icon relative to our application theme, But its not possible in this library.

**Comment by Dhaval2404** [comment]
Add below color resource in your color.xml with your required colors.

```xml
<color name="dialog_choose_icon_color">#757575</color>
<color name="dialog_choose_text_color">#757575</color>
```

**Comment by pankajgurjar747** [comment]
Ok thanks and for title of this dialog? 

By the way thanks for your extra ordinary work....

**Comment by Dhaval2404** [comment]
Add the below line in string.xml file with the required text.

```xml
<string name="title_choose_image_provider">Choose</string>
```

If you're looking for more such text changes. You can override resources from libs [strings.xml](https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/res/values/strings.xml) files.
