### ISSUE TITLE
App crashes with activityNotFoundException camera app is disabled on the device

### ISSUE THREAD

**Issue by gd08xxx** [Dhaval2404/ImagePicker#69]
Step 1) Disable camera app
Step 2) Select camera in the dialog
Step 3) Allow usage of camera
APP crashes with activity not found exception

**Comment by Dhaval2404** [comment]
@gd08xxx I will surely look into it.

**Comment by Dhaval2404** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [App crashes with ActivityNotFoundException camera app is disabled on the device #69](https://trello.com/c/oJzT6hrj/13-app-crashes-with-activitynotfoundexception-camera-app-is-disabled-on-the-device-69)

**Comment by mamomia** [comment]
> Step 1) Disable camera app
> Step 2) Select camera in the dialog
> Step 3) Allow usage of camera
> APP crashes with activity not found exception

having same issue in v1.8 any workaround?
