### ISSUE TITLE
Not working in fragment

### ISSUE THREAD

**Issue by ContextGrid** [Dhaval2404/ImagePicker#7]
Hello Dhaval,

Hope you are doing well, I found that using your library and example it does not work in the fragment, it did not receive in fragment onActivityResult method.

**Comment by Dhaval2404** [comment]
@ContextGrid Thanks for trying out the lib. 

For Fragment, you need to pass Fragment object inside **with** functions.

I suppose you are doing like, inside a fragment
   ` ImagePicker.with(activity) `  // Which is wrong

Please change it to
   `ImagePicker.with(this) //Here this referes to Fragment.`

**Comment by Dhaval2404** [comment]
@ContextGrid Is it working now?

**Comment by felixdivo** [comment]
It works in my fragment just fine using `ImagePicker.with(this)`, with `this is Fragment == true`.

**Comment by Dhaval2404** [comment]
@ContextGrid Closing this task now. Let us know if you are still facing the issue.

**Comment by titosobabas** [comment]
> @ContextGrid Thanks for trying out the lib.
> 
> For Fragment, you need to pass Fragment object inside **with** functions.
> 
> I suppose you are doing like, inside a fragment `ImagePicker.with(activity)` // Which is wrong
> 
> Please change it to `ImagePicker.with(this) //Here this referes to Fragment.`

do you know how to do it on 2022? it looks that way to do it is deprecated
