### ISSUE TITLE
Go back to Gallery after Crop

### ISSUE THREAD

**Issue by jshafer817** [Dhaval2404/ImagePicker#72]
I have spent all day on this! Anyone lend me a hand? I want to go back to the gallery after choosing to crop the photo, instead of the main activity screen, in the sample.. How can i do that?

Something to do with the result code......

This project is very very cool!!

**Comment by Dhaval2404** [comment]
@jshafer817 Do you want to open crop image into the Gallery app or want to open the gallery app to pick another image?

**Comment by jshafer817** [comment]
@Dhaval2404 I just want to go back to the gallery app to pick another image. Thank you soooo much!

**Comment by Dhaval2404** [comment]
@jshafer817 Currently, ImagePicker doesn't support multiple images selection. But you can start the ImagePicker again using Gallary only option. After you receive crop activity result in your main activity.

```kotlin
var imageCounter = 0;
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
     super.onActivityResult(requestCode, resultCode, data)
     if (resultCode == Activity.RESULT_OK) {
      
	imageCounter++;
		
        //Crop Image
        val file:File = ImagePicker.getFile(data)
		
	// Start Gallery App Again
	// Added imageCounter to avoid infinite loop
	if(imageCounter < 2)
		ImagePicker.with(this)
			.crop()
			.galleryOnly()	
			.start()
	}
     } else if (resultCode == ImagePicker.RESULT_ERROR) {
         Toast.makeText(this, ImagePicker.getError(data), Toast.LENGTH_SHORT).show()
     } else {
         Toast.makeText(this, "Task Cancelled", Toast.LENGTH_SHORT).show()
     }
}  
```

**Comment by jshafer817** [comment]
@Dhaval2404 Thanks! I ended up making uCrop always return the filename so I could check it in my mainactivity onactivity result. Thank you!!!


        if (resultCode == Activity.RESULT_OK) {
            Bundle bundle = resultData.getExtras();
            if (bundle != null) {

                if (bundle.get("extra.file_path") != null)
                {
                    Log.d(TAG, "NOTNULL");
                } else ImagePicker.Companion.with(this)
                        .crop()
                        .galleryOnly()
                        .start(102);
            } else Log.d(TAG, "Bundle is NULL");
