### ISSUE TITLE
LICENSE has AOSP in it "Copyright 2019, The Android Open Source Project"

### ISSUE THREAD

**Issue by farmazon3000** [Dhaval2404/ImagePicker#73]
See https://raw.githubusercontent.com/Dhaval2404/ImagePicker/master/README.md. Search for ```Copyright 2019, The Android Open Source Project```.

**Comment by Dhaval2404** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [LICENSE has AOSP in it "Copyright 2019, The Android Open Source Project" #73](https://trello.com/c/7ovboVjT/18-license-has-aosp-in-it-copyright-2019-the-android-open-source-project-73)
