### ISSUE TITLE
Not Working when minifyEnabled is true

### ISSUE THREAD

**Issue by SuketuMerchant** [Dhaval2404/ImagePicker#74]
When enable ProGuard its gone crash, tested on android 10, while creating release signed apk.

**Comment by Dhaval2404** [comment]
@SuketuMerchant Are you able to track any error logs?

**Comment by spatenotte** [comment]
I believe I have stumbled upon the same issue, here are the logs:
![image](https://user-images.githubusercontent.com/5433694/80261556-993a0700-863f-11ea-8852-b4f6549b35e7.png)

**Comment by Dhaval2404** [comment]
@spatenotte Thank you so much for the error logs.

**Comment by spatenotte** [comment]
No problem, happy to help!

**Comment by Dhaval2404** [comment]
Closing this task as InlineActivityResult is removed from ImagePicker v2.0.
