### ISSUE TITLE
why WRITE_EXTERNAL_STORAGE is important? can be removed?

### ISSUE THREAD

**Issue by abdulmannanbutt** [Dhaval2404/ImagePicker#75]
Hi,

I hope you are doing well.

I have used your library and it is awesome. 

But I want to know why you need WRITE_EXTERNAL_STORAGE permission? 

Can't the library use the internal/cache storage? in one of my projects, MVAPT/security team is asking to remove this permission (coz, they think, it is not required for the application). I checked and noticed that It is being merged in the manifest due to this library. 

Can you please help to see?

cc @Dhaval2404

**Comment by Dhaval2404** [comment]
@abdulmannanbutt Thank you for the feedback. 

WRITE_EXTERNAL_STORAGE no longer needed when we use internal/cache storage. I'm currently working on scope storage. Which will make storage permission absolute. 

So in the next version permission will be removed. Thanks

**Comment by abdulmannanbutt** [comment]
Awesome. Waiting for the next release then :)

**Comment by Dhaval2404** [comment]
@abdulmannanbutt I'm planing next release around the end of the month.

**Comment by Dhaval2404** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Storage Permission #75](https://trello.com/c/ZUlx0sli/16-remove-storage-permission-75)

**Comment by enpboss** [comment]
How to mention internal storage in save directory?

**Comment by Dhaval2404** [comment]
@enpboss Can you please explain in detail?

Normally, This will store the image in your app-specific directory

```Kotlin
ImagePicker.with(this)
    //Provide directory path to save images
    .saveDir(getExternalFilesDir(null)!!)
    .start()

**Comment by wonderid** [comment]
how to prevent saving the image to gallery? because I don't need to save it after choose a picture

**Comment by Dhaval2404** [comment]
@wonderid You can provide a directory to save your images. You can also delete the images after the usage if that your requirements.
