### ISSUE TITLE
Minimum SDK

### ISSUE THREAD

**Issue by z85510** [Dhaval2404/ImagePicker#79]
Can you decrease minSdkVersion to 17 in the next version?

Plenty of my users are using SDK 17 and for now, I have to download your library and change it myself

**Comment by kibotu** [comment]
you can use tools override in manifest

`<uses-sdk tools:overrideLibrary="packagename" />`

https://stackoverflow.com/a/27310430/957370

**Comment by Dhaval2404** [comment]
As of now, ImagePicker already provides support for 98.1% of the devices. Sorry, But I will continue to provide support for Android 5.0 and up. 

![image](https://user-images.githubusercontent.com/7314181/102582434-989f3500-4128-11eb-9a60-04f9ead6e68c.png)
