### ISSUE TITLE
Failed to pick Gallery Image

### ISSUE THREAD

**Issue by Deliforce** [Dhaval2404/ImagePicker#8]
Library is awesome. But when i tried to pick an image from Downloads folder then it gives me the above error(Title) and the path was **content://downloads/public_downloads/1511** Using this path am setting this to imageview like this **Imageview.setImageURI**

**Comment by Dhaval2404** [comment]
@Deliforce Thank you very much for trying out the lib. 

It looks like lib is failed to parse ImageUri(content://downloads/public_downloads/1511) into File object.

Will further investigate the issue and try to fix ASAP.

Thank you.

**Comment by Johnsonmaung** [comment]
@Dhaval2404 
GalleryProvider.kt (Line:102)
**val filePath:String? = FileUtils.getPath(activity, uri)**
went wrong.

uri=content://com.android.providers.downloads.documents/document/1310
filePath=null
