### ISSUE TITLE
in Fragment the image preview bitmap is coming very late 

### ISSUE THREAD

**Issue by harishkandekar** [Dhaval2404/ImagePicker#80]
in Fragment the image preview bitmap is coming very late like it takes around 15-20 sec to apprear in preview after activity result

**Comment by Dhaval2404** [comment]
@harishkandekar You must have specified compression and the input image must be very large in size. Can you please provide additional info on this?

**Comment by harishkandekar** [comment]
Actually In activity its working fine within seconds image appears but in fragment its taking too long 

below is the code i am using in fragment 

============================================
 ImagePicker.Companion.with( NormalRegistration.this )// this is fragment
                .cameraOnly()
                .compress( 1024 ) 
                .cropSquare()
                .maxResultSize( 1080, 1080 )   
                .start();

@Override
    public void onActivityResult(int requestCode, int resultCode, @Nullable final Intent data) {
        super.onActivityResult( requestCode, resultCode, data );
        if (resultCode == FragmentActivity.RESULT_OK) {
            //Image Uri will not be null for RESULT_OK
            final Uri fileUri = data.getData();

            try {
                Bitmap bitmap = MediaStore.Images.Media.getBitmap( getContext().getContentResolver(), fileUri );
                Log.d( TAG, "onActivityResult: "+bitmap );
                AsyncTask.execute( new Runnable() {
                    @Override
                    public void run() {
                        //You can get File object from intent

                        File imagefile = new File( data.getData().getPath() );
                     

                        
                    }
                } );

            } catch (IOException e) {
                e.printStackTrace();
            }

            if (resultCode == ImagePicker.RESULT_ERROR) {
                Toast.makeText( getContext(), "Error in clicking or selecting image", Toast.LENGTH_SHORT ).show();
            } else {
                // Toast.makeText( RegistrationActivity.this, "Task Cancelled", Toast.LENGTH_SHORT ).show();
            }
        }

    }

**Comment by Dhaval2404** [comment]
@harishkandekar I suspect, It has nothing to do with library but your code in onActivityResult method.

Specifically this one,

> Bitmap bitmap = MediaStore.Images.Media.getBitmap( getContext().getContentResolver(), fileUri );

**Comment by harishkthedeveloper** [comment]
i removed above lines for bitmap , and tried to load directly file object using glide into imageview but still it is there

**Comment by Dhaval2404** [comment]
@harishkandekar Can you please share onActivityResult Code?

**Comment by harishkandekar** [comment]
`@Override
    public void onActivityResult(int requestCode, int resultCode, @Nullable final Intent data) {
        super.onActivityResult( requestCode, resultCode, data );
        if (resultCode == Activity.RESULT_OK) {
            //Image Uri will not be null for RESULT_OK
            final Uri fileUri = data.getData();

            /*try {*/
                /*Bitmap bitmap = MediaStore.Images.Media.getBitmap( getContext().getContentResolver(), fileUri );
                Log.d( TAG, "onActivityResult: "+bitmap );*/
                AsyncTask.execute( new Runnable() {
                    @Override
                    public void run() {
                        //You can get File object from intent

                        File imagefile = new File( data.getData().getPath() );
                       
                        
                    }
                } );

          

            if (resultCode == ImagePicker.RESULT_ERROR) {
                Toast.makeText( getContext(), "Error in clicking or selecting image", Toast.LENGTH_SHORT ).show();
            } else {
                // Toast.makeText( RegistrationActivity.this, "Task Cancelled", Toast.LENGTH_SHORT ).show();
            }
        }

    }`

**Comment by Dhaval2404** [comment]
@harishkandekar Code with the Glide?

**Comment by harishkandekar** [comment]
File file =  new File( data.getData().getPath() );
            Glide.with( context )
                    .load( file )
                    .into( holder.userimage );

**Comment by harishkandekar** [comment]
just this code i am using to load the image inside activity result in runOnUIthread

**Comment by Dhaval2404** [comment]
```java
Glide.with( context )
   .load(uri) //Directly provide Uri
   .into( holder.userimage );
```
Also, Remove AsyncTask. It's of no use

**Comment by Dhaval2404** [comment]
Also, You don't need to do this
```java
File imagefile = new File( data.getData().getPath() );
```
You can get file object as below:

```java
File file = ImagePicker.Companion.getFile(data);
```

**Comment by harishkandekar** [comment]
Thank you so much , i will try and get back to you

**Comment by harishkandekar** [comment]
its not getting solved , so i used normal camera intent with startavtivityresultfor method in fragment and the problem is solved.
