### ISSUE TITLE
error: cannot access function2

### ISSUE THREAD

**Issue by nobyali** [Dhaval2404/ImagePicker#83]
I cant use request code . it raises cannot access function 2 error..Any solution sir?

**Comment by Dhaval2404** [comment]
Looks like a duplicate of #40

**Comment by Dhaval2404** [comment]
Please use the Default Method over Inline Result:

![image](https://user-images.githubusercontent.com/7314181/81142463-5f48f900-8f8d-11ea-99eb-6ea4af95ed08.png)

Do check the README for more info

**Comment by nobyali** [comment]
I'm using default method...but cant use request code with this

**Comment by Dhaval2404** [comment]
What do you mean by  **cant use request code**. Can you please post error here?

**Comment by nobyali** [comment]
its now resolved sir, thank you very much for this wonderful product..i just removed the inline support implementation...:)
