### ISSUE TITLE
“Failed to create camera image file” when choosing camera or “failed to crop image” when choosing in the library

### ISSUE THREAD

**Issue by muazzam27** [Dhaval2404/ImagePicker#85]
The camera/choose picture function doesn’t work (“failed to create camera image file” when choosing a camera or “failed to crop image” when choosing in the library)

**Comment by Dhaval2404** [comment]
@muazzam27 Did you add android:requestLegacyExternalStorage="true" in manifest file.

**Comment by muazzam27** [comment]
@Dhaval2404 thanks Issue is fixed.
