### ISSUE TITLE
Change String?

### ISSUE THREAD

**Issue by dadou181295** [Dhaval2404/ImagePicker#88]
Hello, how can i override the String "Choose". please thanks :)

**Comment by Dhaval2404** [comment]
Add ```<string name="title_choose_image_provider">Choose</string>``` in your string.xml with desired text.

Please check this [link ](https://github.com/Dhaval2404/ImagePicker/blob/master/imagepicker/src/main/res/values/strings.xml)for string localization. You can override the string as per your need.

**Comment by dadou181295** [comment]
Thanks Boss ! :)
