### ISSUE TITLE
Implement Inline Activity Result

### ISSUE THREAD

**Issue by soareseneves** [Dhaval2404/ImagePicker#9]
Hello, 

First of all thanks for this great library!

I was wondering if you could please make the ImagePicker class open so I can override it, I want to add some way to open activity and get response with lambda which is way more convenient for me.

**Comment by soareseneves** [comment]
Actually, if you could implement this library into yours that would be amazing: https://github.com/florent37/InlineActivityResult

I will do it myself on a forked git and if you enjoy I can do a pull request

**Comment by soareseneves** [comment]
It's already working, I am sure I did not use the best approach but you will get the idea: https://github.com/soareseneves/ImagePicker

Here is an usage example:

`

ImagePicker.with(this)
                    .crop(1f, 1f)	    		//Crop Square image(Optional)
                    .compress(1024)			//Final image size will be less than 1 MB(Optional)
                    .maxResultSize(1080, 1080)	//Final image resolution will be less than 1080 x 1080(Optional)
                    .start { resultCode, data ->
                        if (resultCode == Activity.RESULT_OK) {
                            val fileUri = data?.data
                            imageView.setImage(File(fileUri!!.path), CircleTransform())
                        } else if (resultCode == ImagePicker.RESULT_ERROR) {
                            Toast.makeText(context, ImagePicker.getError(data), Toast.LENGTH_SHORT).show()
                        } else {
                            Toast.makeText(context, "Task Cancelled", Toast.LENGTH_SHORT).show()
                        }
                    }

`

**Comment by soareseneves** [comment]
I made the library optional and added different methods instead of replacing yours to make it backward compatible, people already using your library will still be able to use it as it is even if they update it! I also updated README with this example, please check it out when you can.

**Comment by Dhaval2404** [comment]
@soareseneves Thank you for all your hard work on this. I Will merge the pull request shortly. I truly appreciate your hard work.
