### ISSUE TITLE
Could not find com.github.yalantis:ucrop:2.2.4.

### ISSUE THREAD

**Issue by akhill4054** [Dhaval2404/ImagePicker#90]
While building the app I'm facing this issue (speaking of which, thank you for making this, I'm grateful):

Could not find com.github.yalantis:ucrop:2.2.4.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.4/ucrop-2.2.4.pom
  - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.4/ucrop-2.2.4.pom
Required by:
    project :app > com.github.dhaval2404:imagepicker:1.7.1

**Comment by baransagis** [comment]
Did you add the maven { url "https://jitpack.io" } repository? If so where did you add it?

**Comment by Dhaval2404** [comment]
Maven repo required in the project build.gradle

```
allprojects {
   repositories {
      	jcenter()
        // Make sure to add this in your project for uCrop
       	maven { url "https://jitpack.io" }  
   }
}
