### ISSUE TITLE
Poor image quality

### ISSUE THREAD

**Issue by Dinosane2** [Dhaval2404/ImagePicker#93]
Even without set .compress() or setting .compress(0) the image resulting looks like it WAS indeed compressed. 

Digging I found out that this happens due to CompressionProvider.kt:172 which compress 10% of any jpg without had been instruct to !

There are any reason to this?

        // Check file format
        var format = Bitmap.CompressFormat.JPEG
        var quality = 90
        if (file.absolutePath.endsWith(".png")) {
            format = Bitmap.CompressFormat.PNG
            quality = 100
        }

Kudos for the amazing library, anyway!

**Comment by Dhaval2404** [comment]
@Dinosane2 Good Finding buddy, I will make it 100.
Thank you!
