### ISSUE TITLE
No option to specify Saved image extension to png etc. it always saved as JPG

### ISSUE THREAD

**Issue by akhileshsharma** [Dhaval2404/ImagePicker#94]
Currently when Crop and or compress used or with Camera images there is no option to provide desired image extension while getImageFile method of fileUtils have scope for specifying file extension to save file with desired file extension.  Please fix and update. 

Its a great library and I guess few more small and quick fixes will make it better.

**Comment by akhileshsharma** [comment]
It would be great if just like .saveDir() can include options like .saveFileName() and .saveFileExt()
For .saveFileExt() option values can be restricted to .jpg, .png, .bmp, .jpeg

**Comment by akhileshsharma** [comment]
Wow great! its superfast. I will check it out, hopefully it will fix the issue I am facing.

Thanks a ton bro!




________________________________

"NATION FIRST, JAI HIND"
http://www.innovativebusinessworld.com<http://voicemycampaign.com/join/campaign1>

________________________________

**Comment by Dhaval2404** [comment]
@akhileshsharma I have not released a version yet! Hopefully today or tomorrow I will release a new version after thorough testing.

Thank you!

**Comment by akhileshsharma** [comment]
Yes @Dhaval2404 noticed. Looking forward.

**Comment by Dhaval2404** [comment]
@akhileshsharma Please check out the latest version. Thank you so much for reporting the issue.

**Comment by akhileshsharma** [comment]
Great! Thanks.

**Comment by batadamnjanovic** [comment]
@Dhaval2404 
So, can we change an extension of a file? 
Example: If an image is .png, I want to change it to .jpg.

**Comment by Dhaval2404** [comment]
@batadamnjanovic As of now, We can't do that in lib.
