### ISSUE TITLE
There must be feature of Crop image of already provided URI.

### ISSUE THREAD

**Issue by ashishkumawat** [Dhaval2404/ImagePicker#95]

**Comment by devendra-mcl** [comment]
Hi, Have you found any solution to this library?

**Comment by hitesh-dhamshaniya** [comment]
@devendra-mcl Can you please provide a description of the issue?

**Comment by devendra-mcl** [comment]
This library is perfectly working if I choose to pick and crop an image but if I want to share an image from another app to my app then I get the content Uri and then I don't have the option to crop that image from this Uri. It is a very good feature to provide crop functionality to an existing image from Uri.

**Comment by Dhaval2404** [comment]
@devendra-mcl  Thank you for your feedback. It will be easier to use any crop library to just perform the crop operations. This will help keep the library clean for unnecessary dependencies.

Also, As of now ImagePicker only supports uCrop. If 3rd party library is used directly then the developer will have better control over its customization.
